name: Auto Send Microsoft Teams Message

on:
  #schedule:
    #- cron: '35 2 * * *'  # 09:35 VN time (UTC+7)
    #- cron: '05 8 * * *'  # 15:05 VN time (UTC+7)
  workflow_dispatch:       # Cho phép chạy thủ công

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python team_bot.py

      # - name: Upload screenshots
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: screenshots
      #     path: '*.png'
      
      # - name: Upload debug HTML
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: debug-html
      #     path: '*.html'
      
